# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

env:
    ARTIFACT_NAME: myartifact


jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
            # Artifact name
            name: ${{env.ARTIFACT_NAME }}
            # Destination path
            path: .
      
